# Site settings
author: Antonio Blandin
title: CLI Ruby Project 
header-img: img/home-bg.png
email: antonio.blandin25@gmail.com
copyright_name: Antonio Blandin
description: > # this means to ignore newlines until "baseurl:"
  My first Ruby project
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tonester92

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
